### ISSUE TITLE
Stylize website

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#17]
## Tasks:
- [x] Change background color (check #16) 
- [x] Add fonts for website (check #16) 
- [x] Stylize scroll-up button 
- [x] #14
- [x] #6
- [x] #25 
- [x] #11 
- [x] #10
- [x] #27 
- [x] Add tag for new version (v1.2.0)

**Comment by Nazarii-Melnyk** [comment]
@misha1301 You can create new branches, based on this issue branch. Then just merge another branches from linked issues into this and mark the completed task.

It is necessary also to upgrade version of scalhive-theme repo and make changes in content to correctly apply changes, so there are [issue to update theme version](https://github.com/orgs/TNTU-RS-internship/projects/6?pane=issue&itemId=51275384)

**Comment by misha1301** [comment]
bg-color was changed by @sorokivski, so i just marked this task as done (Change background color)
