### ISSUE TITLE
Add new theme

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#2]
## Tasks
- [x] Choose theme from all templates on [Hugo templates](https://themes.gohugo.io/).
- [x] Clone theme from GitLab repository.
- [x] Copy files from GitLab theme repo in GitHub repo scalhive-theme

### Requirements
1. The style of the theme should be formal.
2. Template must be responsive.
3. Template must be user-friendly.
