### ISSUE TITLE
Change components styles for blog page

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#32]
## Tasks
- [x] Change contact us button
- [x] Change header title font
- [x] Change image right title text 
- [x] Add company name with font identity

**Comment by misha1301** [comment]
"Add company name with font identity" 

I couldn`t find the font so I created two version of the logo with the font.

mobile logo:
![Image](https://github.com/TNTU-RS-internship/scalhive-theme/assets/61250339/dbe132a5-0c82-44a0-8e48-f2948363983c)

desktop logo:
![Image](https://github.com/TNTU-RS-internship/scalhive-theme/assets/61250339/204552b1-b12f-4f60-879e-c910cd3c0d27)
