### ISSUE TITLE
Stylize info components

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#33]
## Tasks
- [x] Add style for language support sorry message
- [x] Fix dual nav bug in 404.html
- [x] Add style for 404 page.
- [x] Add style for thank-you page 
- [x] #40
