### ISSUE TITLE
Fix style bugs

### ISSUE THREAD

**Issue by ya6lis** [TNTU-RS-internship/scalhive-theme#58]
## Tasks description
- A footer line is attached to the "Contact us" button.

![Image](https://github.com/user-attachments/assets/303de95b-0ceb-4ff8-b077-2e06f705297f)

- Not correct DockerHub img color when hover (shoud be blue).

![Image](https://github.com/user-attachments/assets/e0df2b3f-b847-4538-888f-9cacd037277c)

- Links to the map should not be across the entire width of the page.

![Image](https://github.com/user-attachments/assets/bc0e7530-0745-4add-9641-a9a6a0035a3b)

- Remove new-window img.

![Image](https://github.com/user-attachments/assets/61077962-70f1-46d3-bdb6-f37667d6f554)

## Tasks

- [ ] Footer line and "Contact us" button.
- [ ] DockerHub img.
- [ ] Links to the map.
- [ ] Remove new-window img.
