### ISSUE TITLE
Fix styles

### ISSUE THREAD

**Issue by ya6lis** [TNTU-RS-internship/scalhive-theme#63]
## Tasks description

- Make some space in cookies banner in phone version, also check other resolutions and fix style for them.
![Image](https://github.com/user-attachments/assets/968d1982-29a3-4bb0-9373-b741835d8781)

- Add margin for this line to have more space between contacts form and footer.
![Image](https://github.com/user-attachments/assets/10292421-b9fb-4d61-9e87-86232d1c5b2e)

- The size of the banners on the each page must be the same.
![Image](https://github.com/user-attachments/assets/760e2756-53e4-4b5e-aaa9-02ee53108e64)

- Remove all text before footer.
![Image](https://github.com/user-attachments/assets/8266af83-2128-49af-b65f-98b68aaad606)
Shoud look like this 
![Image](https://github.com/user-attachments/assets/4d8c7f08-4fb5-4444-888d-39d5bccf0733)

## Tasks

- [x] Make some space in cookies banner in phone version, also check other resolutions and fix style for them.
- [x] Add margin for this line to have more space between contacts form and footer.
- [x] The size of the banners on the each page must be the same.
- [x] Remove all text before footer.
